-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- This next section is based on recommendations I saw on Youtube
--
-- vim.g.mapleader = " "
--
-- vim.scriptencoding = "utf-8"
-- vim.opt.encoding = "utf-8"
-- vim.fileencoding = "utf-8"
--
-- vim.opt.title = true
